name: "Build and Test - Windows"

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: "Build type"
        required: true
        type: choice
        options:
          - debug
          - release
        default: release
      upload-artifacts:
        description: "Upload unsigned build artifacts"
        required: true
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      platform: windows-latest
      target: x86_64-pc-windows-msvc
      build-args: ${{ inputs['build-type'] == 'debug' && '--debug --target x86_64-pc-windows-msvc' || '--target x86_64-pc-windows-msvc' }}
      asset-prefix: mingtily-windows
      upload-artifacts: ${{ inputs['upload-artifacts'] }}
      is-debug-build: ${{ inputs['build-type'] == 'debug' }}
