name: "Build and Test - macOS"

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: "Build type"
        required: true
        type: choice
        options:
          - debug
          - release
        default: release
      upload-artifacts:
        description: "Upload unsigned build artifacts"
        required: true
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      platform: macos-latest
      target: aarch64-apple-darwin
      build-args: ${{ inputs['build-type'] == 'debug' && '--debug --target aarch64-apple-darwin' || '--target aarch64-apple-darwin' }}
      asset-prefix: mingtily-macos
      upload-artifacts: ${{ inputs['upload-artifacts'] }}
      is-debug-build: ${{ inputs['build-type'] == 'debug' }}
